name: Deploy Master to Pantheon
on:
  push:
    branches: ['master', 'main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Configure SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.17.0
      with:
        php-version: '8.1'
        extensions: imagick, swoole

    - name: Installing Terminus
      run: |
        composer global require pantheon-systems/terminus
        terminus auth:login --machine-token "${{ secrets.PANTHEON_MACHINE_TOKEN }}" -vvv

    - name: Deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
      run: |
        echo ${{ secrets.KNOWN_HOSTS }}
        git remote add pantheon $pantheon_repo
        git push pantheon HEAD:master
        commit_message=$(git log -1 --pretty=%B)
        terminus env:deploy $pantheon_site_name.test --note="Automated deploy: $commit_message"
        terminus env:deploy $pantheon_site_name.live --note="Automated deploy: $commit_message"
